[package]
name = "nitf-viz"
version = "0.1.0"
edition = "2021"
license = "MIT"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
image = "0.25.0"
log = "0.4.21"
nitf-rs = { version = "0.3.0", git = "https://github.com/holmesv3/nitf-rs.git"}
simple_logger = "4.3.3"
